name: kvn_catering
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.5.0
  geolocator: ^10.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.0.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  intl: ^0.18.1
  permission_handler: ^11.0.0
  responsive_framework: ^0.2.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/animations/
    - lib/assets/fonts/
