name: kvn_catering
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  responsive_framework: ^0.2.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/animations/
    - lib/assets/fonts/
